### ISSUE TITLE
環境変数でElasticsearchのSniffingを切り替えられるようにしたい

### ISSUE THREAD

**Issue by ksawaa** [eiicon-company/go-core#17]
## 経緯
DockerでElasticsearchを立てるとSniffing時に無効なホスト名が返ってくるので失敗する。
（single-nodeだからかもしれないです。調査中）

## 詳細
デバッグ時はSniffingをOFFにするか環境変数で切り替えられるようにしたい。
他の手段で解決するべきであれば教えていただけると助かります。

**Comment by ikeikeikeike** [comment]
It would be done correctly, see https://github.com/olivere/elastic/issues/312#issuecomment-402769387
However at the Local-Machine, I would like to use [directly the Elasticsearch](https://www.elastic.co/jp/downloads/elasticsearch) instead of Docker run.
